installation:
  mode: framework-development
  detected_at: '2026-02-03T23:48:45.189Z'
repository:
  url: https://github.com/SynkraAI/aios-core.git
  auto_detect: true
framework:
  source: local
  version: 3.10.0
  location: C:\Users\Ryzen\Desktop\AIOS_CLAUDE\aios-core\node_modules\@aios\fullstack
git_ignore_rules:
  mode: framework-development
  ignore_framework_files: false
